{% set name = "waitress" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 682aaaf2af0c44ada4abfb70ded36393f0e307f4ab9456a215ce0020baefc31f

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - waitress-serve = waitress.runner:run

requirements:
  build:
    - python
    - pip
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests
  imports:
    - waitress
  commands:
    - pip check
    - pytest -v tests
    - waitress-serve --help


about:
  home: https://github.com/Pylons/waitress
  license: ZPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'Production-quality pure-Python WSGI server'
  description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with
    very acceptable performance. It has no dependencies except ones which live
    in the Python standard library. It runs on CPython on Unix and Windows under
    Python 2.7+ and Python 3.3+. It is also known to run on PyPy 1.6.0+ on UNIX.
    It supports HTTP/1.0 and HTTP/1.1.
  doc_url: http://docs.pylonsproject.org/projects/waitress
  dev_url: https://github.com/Pylons/waitress

extra:
  recipe-maintainers:
    - carlodri
    - arishamays1
