travis:
  secure:
    BINSTAR_TOKEN: S09p9/SGxCI9/iOgkf7sk/l9gVe4tuC+yeXtJdXfSZJQm5Pzh1jWLY1W+M98HzBUzQA8wdovaANHQjTs3pNYeDomhF+Y/E956bH2TYpyWPDylvhasUTbaA2TNnG9EJ+pEEBAVX0va5/huBxEvFytcuho4XiQYg/eyZlI8nipdvL5v7Oq2FlxAFIFwBqWHVV6E/fjqml3g9jtorvDkvnjk4w1Ww/eJ1weCQqylCFqB29lmyqy0yNos5SPRDIxTaJxFWBWfh3Kf/7Qog92aB0mvrHHj2+E1YGC96ZJHPN0dSW6AYFzyQGIEq7d05IW6qyKcbBg85NK5tgUgCGQlEBPz9MMVc/CLXCbGsNnL1hFSxYNee/9tUVznjy8xxIYQw9+vwQtM+93ghNCzp1090g2uk+OIakVeGyoL7zbdomapOkgBTy8sJ0AYreariA/fE592a9+fQrjnU0VFHxuKyaYQ9u35JUXS7wWnTmGkMGRHXFWbu5BU4AWQQz/CUm4MorS+K0nuv4ju/2DrYX96/twl2ep9ppFCwFKQ4ILbB98Yhk03IuMhrNafRXgsI3tOgNjEkl3wnPKX7Nk+eXfM4dJX8htoVvFm9QJVxiCfWlE2V+b1Ph9Wk0iqd1nTAUN9mJeFzzncgf4OvNKoSxIo5WgQYK5tAh18wBfvHK0LrG0a3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
