travis:
  secure:
    BINSTAR_TOKEN: b/4IJ/Z+jXGOvtByPrvFoZMHVikmcugQbW3TJreyBJTIsFdShxpF1B/YnHGvylBlFMo6YGtyiPXLXEP+ROQIAkfSx7w/Jf4s+JfyN3NRpVeCN8Jtmrb/3kJa/udbOWvBUQzhUMkfBPNQbvkrsSUvAuVc1AYq34Qpi4HiMSgwVKPZ+CKtxL6qZPre+uYlDqtIlg+T7i0euOdm7R4MVa9QR80ms+zN5oImXRQRJOIUf/ghwmsNSjmSjhSBKs//2YBS9PBEabUM4Fzr8YkkEeB6KuQIL/aBqYqSDFqb31MUxbU3VJV8OUTvNqQQA+LpzEVoTuTmJa6cAFkjtf7jK7h7YUjXDmMNB4o3RG/9TxisS8zWdgVHJXGi26f92vgCN71gaJ3UA2+DMyjm1cyjUC4QFSPGCA32yxnLgjhEYD3o9Q86CE3Z6amqzrrIpHZSMSkBd8Nqky5rrBtB/CdgiDTjd89CiW3827cfgcSsYDFpULTLnq+lL7DtDA25GW/zE+6aNAg9eBgKiJeTgUQjvT8W125LD/roUQKZpTFg+JK9HnSll5auWIxwxDLntsxm/D+bjTex0BGgEEyf6g+aNry3akpwQAOJMqxCvRDqSvyxNrF1DCv9+dfOyrtVGkQ+eS5lYSW/wh75cEWP0IOc41CJuOywb55g0R5LUJDZf2Nhih4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
